### ISSUE TITLE
Scrolling backwards in Circular List Adapter

### ISSUE THREAD

**Issue by nilsi** [ragunathjawahar/adapter-kit#11]
This works great for going down in the list but backwards it's just like a normal list and hits the start. Is there a way to make it work similar the other way around as when scrolling down? Or I have to scroll down far enough when opening the fragment so I'm sure the user wont scroll whole way back to the start? Thanks

**Comment by ragunathjawahar** [comment]
Closing because of [this](https://github.com/ragunathjawahar/circular-list-adapter/issues/2).
